[package]
name = "sts_sim"
version = "0.1.0"
edition = "2021"

[lib]
name = "sts_sim"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
rand = "0.8"
